### ISSUE TITLE
Json数据部分不可见

### ISSUE THREAD

**Issue by Are-sky** [4t145/bilive-danmaku#4]
在按样例中运行后，DanmukuEvent的Json数据中user字段为
`"user":{"uid":0,"uname":"故***","face":null}`
这是否正常？
以下是完整的控制台打印：
`{
	"cmd": "DanmakuEvent",
	"data": {
		"flag": 0,
		"message": {
			"tag": "Plain",
			"data": {
				"message": "要破产啦（"
			}
		},
		"user": {
			"uid": 0,
			"uname": "弦***",
			"face": null
		},
		"fans_medal": {
			"anchor_roomid": 22389206,
			"guard_level": 0,
			"medal_level": 3,
			"medal_name": "自麂人"
		}
	},
	"timestamp": 1689085901635
}`

**Comment by 4t145** [comment]
你指的数据不可见是指uid为0和名字有码吗？还是指face字段为null？
1. 如果是前者，这个问题我没有碰见过，那可能是b站反制野生接口的措施？
2. 如果是后者，弹幕消息的用户的确是不带头像的

**Comment by Are-sky** [comment]
前者，在开始接收弹幕时user字段数据都是有正确数据的，但当过一定时间后，user字段就会变成`"user":{"uid":0,"uname":"故***","face":null}`这样的数据

**Comment by 4t145** [comment]
> 前者，在开始接收弹幕时user字段数据都是有正确数据的，但当过一定时间后，user字段就会变成`"user":{"uid":0,"uname":"故***","face":null}`这样的数据

那可能是没登陆不让看了...

**Comment by 4t145** [comment]
参考这个issue: https://github.com/SocialSisterYi/bilibili-API-collect/issues/732
计划解决方法
- [x] 参考 https://github.com/xfgryujk/blivedm/pull/29
- [ ] 设计登录方案

**Comment by Are-sky** [comment]
ok 我知道怎么解决了

**Comment by Are-sky** [comment]
对Connector，RoomPlayInfoData增加uid字段，然后修改Connector::init方法和Connector::connect两个方法就解决了

**Comment by 4t145** [comment]
> 对Connector，RoomPlayInfoData增加uid字段，然后修改Connector::init方法和Connector::connect两个方法就解决了

直接在auth包里带上主播uid似乎也可以，看这个提交https://github.com/4t145/bilive-danmaku/commit/6ed6d97895da32278afb8bd48c851b18b14897d4
其它项目的issue https://github.com/xfgryujk/blivedm/pull/29

**Comment by 4t145** [comment]
你是在使用这个库吗，我计划周末规范下内部错误处理，把网络请求客户端迁移回reqwest然后发个包

**Comment by Are-sky** [comment]
是的 我fork了一份 用来当我`https://github.com/Are-sky/Stargazing`这个B站直播监听项目的第三方库 现在在自己维护添加了下播事件那些的支持

**Comment by 4t145** [comment]
> 是的 我fork了一份 用来当我`https://github.com/Are-sky/Stargazing`这个B站直播监听项目的第三方库 现在在自己维护添加了下播事件那些的支持

好的，欢迎提pr
